name: Shuttle Deploy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'be/**'
      - '.github/workflows/deploy_be.yml'
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          working-directory: "be"
          cargo-shuttle-version: "0.39.0"
