name: Deploy Frontend

on:
  push:
    branches:
      - 'master'
    paths:
      - 'fe/**'

env:
  API_BASE: 'https://remove-box-rs.shuttleapp.rs/api'

jobs:
  gh_pages:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: ./fe
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'v0.18.6'
      - name: Build
        run: trunk build --release --public-url="//cdn.jsdelivr.net/gh/ommyzhang/remove-box-rs@gh-pages/" --no-sri
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fe/dist
          commit_message: ${{ github.event.head_commit.message }}
